ALTER TABLE public.tickets
    ADD COLUMN IF NOT EXISTS isarchive BOOLEAN NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS isdeleted BOOLEAN NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS removefromrecyclebin BOOLEAN NULL DEFAULT FALSE;
