-- Cash & Bank Phase 1: retail in-store receipts and invoice allocation
-- Release date: 2026-07-31
--
-- Run this complete file once in each environment, then run:
-- npm run verify:finance-foundation
--
-- Do not edit this file after it has been applied to any environment.

BEGIN;

SELECT pg_advisory_xact_lock(hashtext('20260731_cash_bank_retail_receipts'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_bank_allocations_transaction_document
    ON bank_transaction_allocations (
        banktransactionid,
        documenttype,
        documentid
    )
    WHERE status = 'applied';

INSERT INTO finance_schema_versions (version, description)
VALUES (
    '20260731_cash_bank_retail_receipts_v1',
    'Retail in-store receipts and manual sales-invoice allocation'
)
ON CONFLICT (version) DO NOTHING;

COMMIT;
