-- Rental invoice document split:
-- invoiceurl remains the customer-facing summary invoice.
-- supportingdocumenturl stores the detailed itemized invoice generated by the existing document service.

ALTER TABLE revoinvoice
    ADD COLUMN IF NOT EXISTS supportingdocumenturl TEXT,
    ADD COLUMN IF NOT EXISTS summaryinvoicedata JSONB,
    ADD COLUMN IF NOT EXISTS supportingdocumentdata JSONB,
    ADD COLUMN IF NOT EXISTS billingperiodstart DATE,
    ADD COLUMN IF NOT EXISTS billingperiodend DATE,
    ADD COLUMN IF NOT EXISTS billingperiodlabel VARCHAR(32),
    ADD COLUMN IF NOT EXISTS rentaldevicecount INTEGER,
    ADD COLUMN IF NOT EXISTS invoicedocumenttype VARCHAR(50);

ALTER TABLE revoinvoice
    ALTER COLUMN invoiceurl TYPE TEXT;

CREATE INDEX IF NOT EXISTS idx_revoinvoice_rental_billing_period
    ON revoinvoice(orderid, invoicefor, billingperiodstart)
    WHERE LOWER(COALESCE(invoicefor, '')) = 'rental';
