steps:
  # Step 1: Set GCP project
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "config"
      - "set"
      - "project"
      - "revo-dev-and-test"

  # Step 3: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/revo-dev-and-test/revo365-sit-backend:latest"
      - "."

  # Step 4: Push the Docker image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/revo-dev-and-test/revo365-sit-backend:latest"

  # Step 5: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "revo365-sit"
      - "--image"
      - "gcr.io/revo-dev-and-test/revo365-sit-backend:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--execution-environment"
      - "gen2"
      - "--service-account"
      - "revotestbackend@revo-dev-and-test.iam.gserviceaccount.com"
      - "--set-env-vars"
      - "GCP_PROJECT_ID=${_GCP_PROJECT_ID}, GCP_PROJECT_LOCATION=${_GCP_PROJECT_LOCATION},GCP_PROJECT_QUEUE=${_GCP_PROJECT_QUEUE},GCP_TASK_URL=${_GCP_TASK_URL},GMAIL_AUTH_PASSWORD=${_GMAIL_AUTH_PASSWORD},GMAIL_AUTH_USER=${_GMAIL_AUTH_USER},GMAIL_HOST=${_GMAIL_HOST},GMAIL_PORT=${_GMAIL_PORT},GMAIL_SERVICE=${_GMAIL_SERVICE},POSTGRES__DATABASE=${_POSTGRES__DATABASE},POSTGRES_HOST=${_POSTGRES_HOST},POSTGRES_PASSWORD=${_POSTGRES_PASSWORD},POSTGRES_PORT=${_POSTGRES_PORT},POSTGRES_USER=${_POSTGRES_USER},POSTGRESS_QUERY_API=${_POSTGRESS_QUERY_API},REDIRECT_INVENTORY_URL=${_REDIRECT_INVENTORY_URL},REDIRECT_URL_FAILURE=${_REDIRECT_URL_FAILURE},REDIRECT_URL_PAYMENT_STATUS=${_REDIRECT_URL_PAYMENT_STATUS},REDIRECT_URL_SUCCESS=${_REDIRECT_URL_SUCCESS},REDIS_EMAIL_OTPEXPSEC=${_REDIS_EMAIL_OTPEXPSEC},REDIS_HOST=${_REDIS_HOST},REDIS_PASSWORD=${_REDIS_PASSWORD},REDIS_PORT=${_REDIS_PORT},REDIS_SESSIONEXSEC=${_REDIS_SESSIONEXSEC},ENV_RAZORPAY_KEY_ID=${_ENV_RAZORPAY_KEY_ID},ENV_RAZORPAY_KEY_SECRET=${_ENV_RAZORPAY_KEY_SECRET}, SHIPROCKET_EMAIL=${_SHIPROCKET_EMAIL}, SHIPROCKET_PASSWORD=${_SHIPROCKET_PASSWORD}, SHIPROCKET_BASE_URL=${_SHIPROCKET_BASE_URL}, ENV_GOOGLE_API_KEY=${_ENV_GOOGLE_API_KEY}, ENV_GOOGLE_LOCATION_ID=${_ENV_GOOGLE_LOCATION_ID},ENQUIRY_SHEETS_WEBHOOK_URL=${_ENQUIRY_SHEETS_WEBHOOK_URL}, ENQUIRY_SHEETS_SECRET=${_ENQUIRY_SHEETS_SECRET}, ENQUIRY_CORPORATE_SHEET=${_ENQUIRY_CORPORATE_SHEET}, ENQUIRY_INDIVIDUAL_SHEET=${_ENQUIRY_INDIVIDUAL_SHEET}, ENV_RAZORPAY_WEBHOOK_SECRET=${_ENV_RAZORPAY_WEBHOOK_SECRET}, ENV_INTERNAL_TASK_SECRET=${_ENV_INTERNAL_TASK_SECRET}, ENV_SHIPROCKET_WEBHOOK_TOKEN=${_ENV_SHIPROCKET_WEBHOOK_TOKEN}"

# Substitution variables matched exactly to  env
substitutions:
  _GCP_PROJECT_ID: "${GCP_PROJECT_ID}"
  _GCP_PROJECT_LOCATION: "${GCP_PROJECT_LOCATION}"
  _GCP_PROJECT_QUEUE: "${GCP_PROJECT_QUEUE}"
  _GCP_TASK_URL: "${GCP_TASK_URL}"
  _GMAIL_AUTH_PASSWORD: "${GMAIL_AUTH_PASSWORD}"
  _GMAIL_AUTH_USER: "${GMAIL_AUTH_USER}"
  _GMAIL_HOST: "${GMAIL_HOST}"
  _GMAIL_PORT: "${GMAIL_PORT}"
  _GMAIL_SERVICE: "${GMAIL_SERVICE}"
  _POSTGRES__DATABASE: "${POSTGRES__DATABASE}"
  _POSTGRES_HOST: "${POSTGRES_HOST}"
  _POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  _POSTGRES_PORT: "${POSTGRES_PORT}"
  _POSTGRES_USER: "${POSTGRES_USER}"
  _POSTGRESS_QUERY_API: "${POSTGRESS_QUERY_API}"
  _REDIRECT_INVENTORY_URL: "${REDIRECT_INVENTORY_URL}"
  _REDIRECT_URL_FAILURE: "${REDIRECT_URL_FAILURE}"
  _REDIRECT_URL_PAYMENT_STATUS: "${REDIRECT_URL_PAYMENT_STATUS}"
  _REDIRECT_URL_SUCCESS: "${REDIRECT_URL_SUCCESS}"
  _REDIS_EMAIL_OTPEXPSEC: "${REDIS_EMAIL_OTPEXPSEC}"
  _REDIS_HOST: "${REDIS_HOST}"
  _REDIS_PASSWORD: "${REDIS_PASSWORD}"
  _REDIS_PORT: "${REDIS_PORT}"
  _REDIS_SESSIONEXSEC: "${REDIS_SESSIONEXSEC}"
  _ENV_RAZORPAY_KEY_SECRET: "${ENV_RAZORPAY_KEY_SECRET}"
  _ENV_RAZORPAY_KEY_ID: "${ENV_RAZORPAY_KEY_ID}"
  _SHIPROCKET_EMAIL: "${SHIPROCKET_EMAIL}"
  _SHIPROCKET_PASSWORD: "${SHIPROCKET_PASSWORD}"
  _SHIPROCKET_BASE_URL: "${SHIPROCKET_BASE_URL}"
  _ENV_GOOGLE_API_KEY: "${ENV_GOOGLE_API_KEY}"
  _ENV_GOOGLE_LOCATION_ID: "${ENV_GOOGLE_LOCATION_ID}"
  _ENQUIRY_SHEETS_WEBHOOK_URL: "${ENQUIRY_SHEETS_WEBHOOK_URL}"
  _ENQUIRY_SHEETS_SECRET: "${ENQUIRY_SHEETS_SECRET}"
  _ENQUIRY_CORPORATE_SHEET: "${ENQUIRY_CORPORATE_SHEET}"
  _ENQUIRY_INDIVIDUAL_SHEET: "${ENQUIRY_INDIVIDUAL_SHEET}"
  _ENV_RAZORPAY_WEBHOOK_SECRET: "${ENV_RAZORPAY_WEBHOOK_SECRET}"
  _ENV_INTERNAL_TASK_SECRET: "${ENV_INTERNAL_TASK_SECRET}"
  _ENV_SHIPROCKET_WEBHOOK_TOKEN: "${ENV_SHIPROCKET_WEBHOOK_TOKEN}"

options:
  logging: CLOUD_LOGGING_ONLY
