const date = new Date();

let day = date.getDate();
let month = date.getMonth() + 1;
let year = date.getFullYear();

let currentDate = `${day}-${month}-${year}`;
export let poData = [
  {
    poNumber: "AUTOGENERATED",
    companyName: "Cloud desk",
    companyAddress: "Ratha tek Meadows",
    contactName: "XYZ ",
    phoneNumber: 1234566777,
    gstNumber: "12kjfdjsdrt4e40",
    io_companyName: "XYZ",
    io_companyAddress: "Mumbai",
    io_contactName: "XYZ ",
    io_phoneNumber: 1234566777,
    io_gstNumber: "12kjfdjsdrt4e40",
    dt_companyName: "kansdsfs",
    dt_companyAddress: "Hydrabad",
    dt_contactName: "XYZ ",
    dt_phoneNumber: 1234566777,
    dt_gstNumber: "12kjfdjsdrt4e40",
    supplier: 1,
    product: [{
      id: 1,
      Name: "Apple",
      unitPrice: 1000000,
      quantity: 10,
      totalPrice: 10000000
    },
    {
      id: 2,
      Name: "hp",
      unitPrice: 40000,
      quantity: 5,
      totalPrice: 200000
    },],
    subTotal: 80000000,
    discount: 0,
    sgst: 10000,
    cgst: 10000,
    payableTaxAmount: 20000,
    total: 80020000,
    createdDate:123546657,
    modifiedDate:124333565,
  },
];
